// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyatgncctzrinruqiyia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5YXRnbmNjdHpyaW5ydXFpeWlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODUyNzQsImV4cCI6MjA3MTc2MTI3NH0.1HLewPvJeTVCqISFYevLZ13cW9rp5JluIlMa2yLkFQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});